---
bibliography: Biblio.bib
---

\addtocontents{toc}{\protect\setcounter{tocdepth}{1}}
\newpage

# Présentation du sujet {.unnumbered}

------------------------------------------------------------------------

## Contextualisation {.unnumbered}

Depuis 2022, la situation politique française est particulièrement instable. Les élections législatives ayant suivi la dissolution n’ont pas permis de dégager une majorité absolue. Néanmoins, le gouvernement réussit, jusqu’en 2024 à trouver une majorité ou à défaut à faire passer des textes notamment grâce à l’article 49-3 de la constitution.[@breteauAvecVingttroisRecours] La dissolution post campagne européenne n’a pas permis au camp présidentiel de retrouver sa majorité au parlement, pire, plus aucune majorité claire n’est identifiable. On observe, dès lors, une instabilité gouvernementale caractérisée par la succession de gouvernements de courte durée. Alors, cette période politique sans précédent en devient particulièrement floue pour les citoyens. Les gouvernements se succèdent, les alliances se font et se défont, et le citoyen pour qui la politique n’est ni le métier, ni le sujet d’étude ou d’intérêt peut très rapidement s’en trouver perdu. Dans ce contexte, les médias jouent un rôle particulièrement important dans la vie démocratique du pays. Informer, interpréter, donner des clés de lecture synthétique aux citoyens devient essentiel pour la vie démocratique.

Aussi, ces médias dont le rôle semble si important, d’autant plus aujourd’hui, sont confrontés à une défiance croissante de la part des citoyens. Selon le baromètre de référence La Croix Kantar, 56% des Français estiment que les médias ne sont pas fiables, en 2022. Quatre grandes causes apparentes semblent expliquer cette défiance.[@migotMediasGrandeDefiance2023] D’abord, la mise en spectacle croissante de l’information. Il ne s’agit plus de diffuser l'information brute mais de la rendre attractive. Ensuite, la défiance viendrait de la concentration des médias entre les mains de huit milliardaires[@migotMediasGrandeDefiance2023], donc d’une sorte d’oligarchie pour qui les médias serviraient les intérêts. Ceux-ci représentent 81% de la diffusion des quotidiens nationaux et 95% de celle des hebdomadaires nationaux[@migotMediasGrandeDefiance2023]. Par ailleurs, la crédibilité des médias serait mise en cause par la propagation maladroite de fake news et différents scandales comme celui de Cambridge Analytica qui ferait grandir une méfiance de l’information en général. Finalement, cette méfiance serait un des effets de la perte de confiance des citoyens envers l’ensemble des institutions démocratiques.

Néanmoins, on observe face à cette défiance, une montée en puissance de nouveaux médias : les médias numériques et indépendants. Ces derniers se caractérisent par leur liberté face à l’influence de gouvernements et/ou acteurs externes comme une entreprise privée ou une personne influente. Généralement, ils appartiennent à leurs salariés.[@JournalismeIndependantQuoi2021] $^,$  [ @MediasIndependantsMasterclass2023] Aussi, les médias indépendants numériques sont des médias indépendants utilisant les nouvelles technologies comme plateforme d’information ce qui leur permet de toucher un public toujours plus large. L’évolution du nombre d’abonnés de la chaîne YouTube du média *Blast, Le souffle de l’info* illustre bien cette tendance en passant de 300 000 abonnés en novembre 2021 à 1,5 million en août 2025.[@YoutuberBLASTSouffle] Nous nous proposons de nous interroger sur ces derniers afin de comprendre les différentes raisons et enjeux de leur développement.

## Définition des principaux concepts {.unnumbered}

L’analyse des évolutions du champ médiatique contemporain impose de revenir, dans un premier temps, sur la structuration traditionnelle du champ journalistique. En s'attachant à comprendre ce qu'a pu être le journalisme et ses mutations, nous pourrons appréhender de façon plus pertinente sa forme actuelle. Nous mobilisons ici le concept de champ tel qu’élaboré par Pierre Bourdieu. En rupture avec la sociologie américaine fonctionnant par typologies, c’est-à-dire par classement des agents sociaux dans des cases fixes et statiques, le concept de champ se veut, lui, mouvant.[@bourdieuSeminairesConceptChamp2013] À défaut de classer les populations, ce concept invite à s’intéresser aux positions des agents sociaux et aux relations entre ces positions. Ainsi, les frontières du concept de champ se veulent volontairement floues dans la mesure où leur définition consiste en un enjeu de lutte.[@bourdieuSeminairesConceptChamp2013] Par exemple, considérer un critique d’art comme un « vrai » intellectuel ou un simple journaliste fait partie de la lutte interne au champ intellectuel. Le champ journalistique n’échappe pas à cette tension et il est nécessaire d’étudier son histoire pour comprendre son fonctionnement actuel.

Aussi, bien que les frontières de ce champ soient floues, notamment à l’ère d’Internet permettant l’émergence d’un journalisme citoyen par qui souhaite devenir producteur d’informations, il est possible de construire le champ journalistique comme une opposition entre des médias dominants et des médias alternatifs. Les premiers sont définis par des ancrages historiques dans des logiques professionnelles strictes et des supports particuliers (TV, radio, presse écrite).[@dufourYouTubeContestataire2024] Ils sont dits dominants car hégémoniques dans ce champ. Ces médias sont aussi définis par leur soumission à des champs exogènes au champ médiatique. Le champ économique en est un bon exemple dans la mesure où il impose une logique de marché aux médias dominants qui se trouvent être dans une recherche constante d’audimat, de satisfaction des annonceurs et de vente, ce qui les pousse à produire une information commerciale plutôt qu’intellectuelle.[@bourdieuLempriseJournalisme1994] Cette dépendance à des champs externes au champ journalistique définit ce que Bourdieu qualifie de caractère hétéronome des médias dominants.[@bourdieuLempriseJournalisme1994] Les normes imposées aux médias dominants ne sont pas issues seulement du champ journalistique.

Quant à eux, les médias alternatifs se définissent en opposition aux médias dominants et forment des « médiactivistes » c’est-à-dire des médias allant de la critique pure de la doxa et du champ journalistique à la production autonome d’information.[@cardonMediactivistes] Ils se veulent engagés[@aubertParadoxeJournalismeParticipatif2009] et rejettent l’apparente neutralité qui caractérise en partie les médias dominants. Ces médias existent notamment sur Internet et concurrencent de plus en plus le pouvoir de gatekeeping (concept sur lequel nous reviendrons, par la suite, dans l'état de l'art) des dominants.[@neveuSociologieJournalisme] Afin de comprendre l’émergence de ces médias alternatifs numériques et leur fonctionnement contemporain, nous proposons de suivre un cheminement chronologique de l’évolution du champ journalistique particulièrement impacté par l'avènement et la démocratisation d’Internet, et par une crise interne économique et de légitimité. Afin de réaliser au mieux cette tâche, il est nécessaire de se plonger dans la littérature existante. C'est ce que l'état de l'art suivant se propose d'accomplir.
