---
bibliography: Biblio.bib
---

\newpage
\addtocontents{toc}{\protect\setcounter{tocdepth}{1}}

# Etat de l'art {#sec-etat-art .unnumbered}

## Le champ journalistique dominant subit une crise structurelle {.unnumbered}

### Prenant ses racines dans la notion de Gatekeeping et dans sa structure économique.{.unnumbered}

D’abord, la composition dominante du monde médiatique est issue de la fusion des deux modèles originaux de la presse moderne. D’une part, comme le rappelle Erik Neveu, le modèle anglo-saxon qui se fondait sur cinq piliers majeurs : l’importance de la collecte d’informations, l’importance de l’information objective, un utilitarisme revendiqué (choix éditoriaux assumés), un modèle économique entrepreunarial avec une forte composante liée à la publicité, et un statut de journaliste salarié et payé au rendement. D’autre part, il y avait le modèle français dans lequel la qualité du journaliste était reconnue à travers ses talents de polémiste et ses qualités stylistiques. Le journaliste français n'était pas celui du terrain, mais celui de la pensée.[@neveuSociologieJournalisme] Au fur et à mesure du temps, les deux modèles ont fini par s’influencer l’un l’autre jusqu’à fusionner. Alors, à travers ce fonctionnement, les médias dominants se plaçaient en tant que « Gatekeepers » des informations.[@neveuSociologieJournalisme] En effet, ce concept mobilisé par Neveu montre comment par leur contrôle des canaux de diffusion tels que les journaux écrits puis la radio et la télévision, les médias dominants étaient les seuls décideurs des informations qui doivent ou non être diffusées. Dans ce système, le citoyen n’a, dès lors, qu’un rôle de spectateur et n’a aucun impact sur l’information qu’il reçoit ce qui sous-entend une confiance envers le professionnel de l’information qu’est le journaliste.[@neveuSociologieJournalisme]

Aussi, le journalisme s’est professionnalisé et répond désormais à des logiques de marché par son fonctionnement fondé sur les publicités. La volonté de diffuser des informations pertinentes et objectives a été délaissée car est soumise à un besoin de capitalisation sur les statistiques : plus le média est diffusé, regardé ou acheté, plus il gagne d’argent. Or le développement d’Internet a mis en branle ce système économique selon plusieurs raisons. D’abord, un changement de culture des consommateurs. Internet est devenu une place forte de la diffusion d’informations. Or cette diffusion en ligne est souvent gratuite ce qui décourage les anciens consommateurs à payer leurs journaux.[@neveuSociologieJournalisme] Aussi, les GAFAM et notamment les réseaux sociaux numériques touchent des milliards de personnes donc attirent les publicités bien plus que les médias dominants. Alors, les médias ont adopté un journalisme de marché qui se caractérise par la coupe dans les effectifs, la précarisation des journalistes et la concentration des “soft news” rentables. Cette stratégie qui consiste à produire plus avec moins a souvent baissé la qualité de l’information sans pour autant avoir pu restaurer une rentabilité durable et induit donc une perte de confiance du consommateur envers les journalistes.[@neveuSociologieJournalisme]

Finalement, au-delà de ne connaître qu’une crise économique, le champ journalistique vit aussi une crise de confiance. Comme dit précédemment les médias dominants sont possédés aujourd’hui à plus de 81% par huit milliardaires en France.[@migotMediasGrandeDefiance2023] Dans le passé, il existait notamment aux États-Unis une tradition qui voulait que les rédactions considérées comme sacrées et les directions d’entreprises soient complètement hermétiques. Or aujourd’hui, cette tradition s’est perdue ce qui pose des suspicions de censure, de nominations complaisantes, marquant une prise de pouvoir de l’entreprise commerciale sur l’entreprise d’information. Le public et les journalistes conscients de ces enjeux ont pu alors faire le choix de se détourner des médias dominants.[@neveuSociologieJournalisme]

### La réaction à cette crise se fait par l’émergence de médiactivistes voulant redonner ses pouvoirs au champ journalistique.{.unnumbered}

Face aux défaillances du système médiatique dominant, certains journalistes et une partie du public sont devenus de réels médiactivistes. En effet, le concept peut être élargi et comprendre alors toutes les mobilisations sociales progressistes qui orientent leur action vers la critique des médias dominants et/ou la création de médias alternatifs.[@cardonMediactivistes] Cette définition plus large permet d’y intégrer la formation de médias amateurs participatifs tels que AgoraVox ou Rue89. Cette réaction épidermique d’une partie des acteurs et des spectateurs prend racine dans une volonté de replacer les pouvoirs des journalistes au centre de leur profession, la défaillance du champ journalistique étant perçue comme un risque démocratique pour la société dans son ensemble.[@bourdieuLempriseJournalisme1994]

Les pouvoirs du journalisme sont parfois fantasmés ou exagérés. Une première vision simpliste mais commune du champ journalistique dominant consiste à lui attribuer des pouvoirs très forts. De vieilles théories sociologiques dépassées dépeignent un public passif chez qui les médias pourraient agir comme une « piqûre hypodermique »[@neveuSociologieJournalisme] en transmettant des messages sans qu’aucune analyse critique ne soit faite par les récepteurs. Cette vision est parfois complétée par la psychologie des foules de Gustave Le Bon, d'après Erik Neveu, pour qui le peuple est irrationnel et manipulable. En réalité, la sociologie de la réception démontre que le public n’est pas passif. Il filtre et interprète les messages selon sa classe sociale et sa culture.[@neveuSociologieJournalisme] Néanmoins, bien que le pouvoir d’influence direct des médias dominants soit limité, ils possèdent un pouvoir structurel fort qui s’incarne à travers trois mécanismes principaux. D’abord, ils ont le pouvoir de choisir leur agenda et leur angle d’approche des sujets sélectionnés. De fait, bien qu’ils ne puissent pas dire aux gens ce qu’ils doivent penser, ils peuvent cependant leur imposer ce à quoi ils doivent penser. Le choix de l’angle d’approche peut biaiser les opinions et structurer une vision du monde. De plus, les médias dominants ont un pouvoir de consécration culturelle dans la mesure où le traitement médiatique d’un livre ou d’un artiste peut faire ou défaire son succès. Alors, on observe un changement dans les règles de légitimité intellectuelle en valorisant les « tuttologi »[@neveuSociologieJournalisme] (les tutologues ou experts en tout) au détriment des chercheurs reconnus par leurs pairs car plus enclins à répondre aux nombreuses demandes des journalistes, même sur des sujets qui ne sont pas de leur domaine de compétence. Finalement, leur dernier pouvoir se fonde sur les sondages. En effet, bien qu’ayant perdu le monopole de la parole publique à cause de l'avènement du numérique, les médias dominants utilisent les sondages pour opposer une « vox populi » scientifique.[@neveuSociologieJournalisme]

Finalement, considérant ces pouvoirs du champ journalistique comme étant essentiels pour la vie démocratique, la crise économique et structurelle du monde journalistique, et la détention des médias par quelques milliardaires ayant leurs propres intérêts et parfois leurs agendas éditoriaux, certains journalistes et une partie du public ont travaillé dans le sens de l’émergence d’une réaction citoyenne face aux manquements institutionnels et au blocage des canaux de dialogue civique.[@seddaRessortsDemocratiquesMedias2017] Cette réaction se fait notamment sur les plateformes numériques, d’abord selon un modèle participatif dans lequel les citoyens anciennement spectateurs deviennent acteurs.

## Cette émergence de médiactivistes s'appuie sur la démocratisation du numérique. {.unnumbered}

### En permettant la naissance des médias participatifs dans lesquels le public est actif. {.unnumbered}

Face aux défaillances perçues du système médiatique, Dominique Cardon et Fabien Granjon identifient deux courants majeurs structurant le « médiactivisme » : la critique contre-hégémonique et le courant expressiviste.[@cardonMediactivistes] Les partisans de la critique contre-hégémonique partent du postulat que les médias dominants sont des vecteurs de propagande au service du champ économique et politique. Dès lors, ils imposent une domination symbolique et une pensée unique, uniformisée. L’objectif pour ceux-là est donc de briser cette hégémonie en explicitant les structures de pouvoirs en emprise sur le champ journalistique afin de produire une information différente mais qui respecte réellement les codes déontologiques journalistiques (exactitude, investigation et temps long) à travers de nouveaux médias. L’approche se veut donc structurelle, valorisant les enjeux globaux et de classe, et s’appuyant sur une professionnalisation du militantisme à travers une rigueur quasi-scientifique sans se cacher derrière une pseudo-neutralité considérée comme un mythe.[@cardonMediactivistes]

Quant à eux, les partisans du courant expressiviste considèrent que le problème du journalisme ne se trouve pas dans des questions structurelles ou dans des questions de contenu mais plutôt dans la coupure imposée entre ceux qui parlent et ceux qui écoutent. Le système médiatique est alors perçu comme confisquant la parole. L’objectif est donc l’empowerment du citoyen à travers la mise en place de structures participatives dans lesquelles l’approche subjective, l'amateurisme et le refus des hiérarchies professionnelles (tout le monde peut être journaliste) sont promus.[@cardonMediactivistes] C’est ce courant qui émerge principalement dans les années 2000-2010 à travers des sites tels que *AgoraVox* ou *Rue89*.[@ho-dacSubjectiviteTraversMedias2011]

Ce courant participatif prend ses racines dans celles du médiactivisme. Originellement, la première trace de médiactivisme remonte au Parti-Journal (modèle léniniste) dont le but n’est pas informationnel mais s’inscrit dans une logique de construction du parti révolutionnaire en créant un réseau de distribution militant entre ouvriers d’une information très descendante (du comité aux ouvriers).[@cardonMediactivistes] On retrouve déjà cette logique d'empowerment de l’ouvrier (puis du citoyen) qui est fondamentale. Dans les années 60-70 et notamment après mai 68 où l’on observe une explosion du cinéma militant grâce aux progrès technologiques (caméras 16mm, vidéo), on voit l’émergence de deux courants : les professionnels (incarnés par Marker notamment) qui veulent mettre leur savoir-faire au service de la cause mais qui sont accusés d’exploiter les ouvriers en les filmant sans leur donner la parole, et les participationnistes (incarnés par Medvedkine) qui souhaitent casser la division du travail en donnant directement la caméra aux ouvriers dans l’objectif de la création de leurs propres films, on parle de cinéma d’intervention sociale.[@cardonMediactivistes] Alors, malgré deux visions différentes sur la forme, sur le fond on observe que l’ouvrier devient central et acteur (passif ou actif selon l’école, mais acteur quand même) dans la création d’informations. En parallèle, dans les années 70, on observe une mutation du modèle léniniste dans le Chili d’Allende. Contrairement à ce dernier qui cherchait à imposer une vérité, Allende cherche à gagner une bataille culturelle. Il adopte la stratégie du contenu implicite qui consiste à diffuser ses valeurs socialistes non pas à travers les médias dominants mais plutôt à travers des comics, des romans-photos ou encore des magazines féminins populaires.[@cardonMediactivistes] Il recherche l'alternative aux médias dominants en multipliant les canaux de diffusion. C’est à partir de ces bases : empowerment du citoyen et multiplication des canaux de diffusion qu’émerge dans les années 80-90 un Internet militant.

En 1978 est publié le rapport Nora-Minc qui définit le concept de *télématique*, mot-valise formé par *télécommunications* et *informatique*, qui dans la lignée des évolutions précédemment explicitées, souligne la nécessité d’une information horizontale pour éviter le rejet du pouvoir. Alors, avant même la naissance du web grand public, on observe sur les premiers appareils mis en réseaux la formation de mouvements sociaux auto-organisés comme celui des infirmières en France dans l’année 1988.[@cardonMediactivistes] Dès le début des années 2000 et la popularisation de l’Internet grand public, ces enjeux militants et cette nouvelle philosophie médiatique vont s'incarner dans des médias web participatifs rompant définitivement la distinction stricte entre producteurs et consommateurs d’information.[@aubertParadoxeJournalismeParticipatif2009]

### Des médias participatifs dont la découverte des limites a permis la transition vers les médias alternatifs numériques. {.unnumbered}

D’abord, ces médias web participatifs ont pour moteur la défiance envers les médias traditionnels. Cette défiance est historique et issue des défaillances du champ journalistique dominant évoquées antérieurement. Par ailleurs, cette critique des médias dominants se fait selon trois pans. On y retrouve la critique de l’uniformité, d’un « règne du “consensus” et des “idées reçues” ».[@aubertParadoxeJournalismeParticipatif2009] Mais aussi, un soupçon de partialité par leur dépendance aux différents champs économiques, politiques et industriels.[@aubertParadoxeJournalismeParticipatif2009]$^,$ [@bourdieuLempriseJournalisme1994] Et finalement, la volonté de dévoilement, de rompre le silence de la doxa médiatique sur des inégalités sociales ignorées ou des « réalités cachées ». La naissance de ces nouveaux médias type AgoraVox rompt avec la passivité du passé des consommateurs qui a l’opportunité de devenir acteur.[@aubertParadoxeJournalismeParticipatif2009] Ces médias participatifs émergent et s’inscrivent dans une logique expressiviste. Ils sont dans une démarche de fact-checking des médias dominants, ils deviennent les « Watchdogs », chiens de garde du respect des codes déontologiques et de la rigueur journalistique, a priori non respectés par les médias dominants.[@cardonMediactivistes] Le concept de Gatekeeping se meut en Gatewatching, c’est-à-dire une surveillance et un tri du flux continu d'informations inhérent à l'immédiateté imposée par le numérique.[@neveuSociologieJournalisme]

À travers ces médias participatifs, la technologie qui était jusqu’alors une contrainte devient une opportunité. En effet, la radio ou la télévision représentaient des barrières nettes entre le consommateur et le producteur, sauf cas exceptionnel type radios pirates. Le développement des technologies numériques entraîne une diffusion à moindre coût et une fusion entre information et mobilisation. La coordination se fait par le bas, elle est décentralisée et auto-organisée, poussant donc l’individu actif vers le militantisme.[@cardonMediactivistes] Néanmoins, ces médias participatifs bien qu’ayant un impact sur le rapport des consommateurs à l’information restent limités dans l’alternative qu’ils proposent aux médias dominants. En effet, paradoxalement les médias participatifs, bien qu’ils critiquent les médias traditionnels, n’existent qu’à travers eux car ils s’appuient massivement dessus pour produire leurs propres contenus.[@aubertParadoxeJournalismeParticipatif2009] Aussi, l'idéal du journalisme citoyen se heurte à la réalité empirique. Les travaux d'Aurélie Aubert sur les rédacteurs des nouveaux médias montrent que les contributeurs des médias participatifs font peu de reportages ou d’enquêtes. Leur travail est presque seulement la compilation de sources web et du fact-checking des médias dominants.[@aubertParadoxeJournalismeParticipatif2009]

Finalement, c’est face à cette situation que les médias alternatifs ont tout leur intérêt. Alors même que l’ère post-média est arrivée (chacun peut devenir son propre média) la concentration des médias et leur pouvoir sur la société restent forts car bien qu’Internet ait élargi le cercle des producteurs, il a aussi recréé des hiérarchies oligarchiques dans la mesure où les plus visibles restent les plus puissants.[@cardonMediactivistes] Alors, on observe l’émergence de médias alternatifs professionnels et institutionnalisés dans les années 2010, soutenant une ligne éditoriale engagée et militante, qui retiennent les leçons des médias participatifs en délaissant en partie l’expressivisme de tous dans le but de produire une information originale et détachée des médias dominants.[@jouxPurePlayersMedias2022b]

## Ces médias alternatifs numériques qui sont en quête de légitimité. {.unnumbered}

### Se fondent sur une hybridation professionnel / amateur en retenant les leçons des médias participatifs, et sur des modèles économiques innovants. {.unnumbered}

Le modèle mis en place par Mediapart en 2009 va infuser sur le reste du champ médiatique alternatif, il paraît donc nécessaire de s’attarder sur son fonctionnement. D’abord, selon Roland Canu et Caroline Datchary, Mediapart s’appuie sur une hybridation professionnel - amateur.[@canuJournalistesLecteurscontributeursMediapart2010] En effet, d’une part Mediapart emploie des journalistes professionnels pour mener ses enquêtes. D’autre part, les abonnés qui peuvent être universitaires, journalistes eux-mêmes ou citoyens informés complètent ou corrigent les enquêtes et articles des journalistes professionnels. En quelque sorte, on observe un retour au Gatekeeping mais un Gatekeeping partagé car le pouvoir de filtrer une information non pertinente n’est pas qu’entre les mains du journaliste. Il est partagé entre la rédaction et la communauté qui peut imposer précisions, ajouts ou reformulations.[@canuJournalistesLecteurscontributeursMediapart2010] Par ailleurs, les abonnés de Mediapart constituent son modèle économique. En effet, ce média n’est financé que par les abonnements de ses consommateurs. Alors, il évite toutes les problématiques liées à un financement par la publicité qui y est complètement rejetée. En complément des abonnements, le don est valorisé comme un soutien citoyen permettant de financer des projets supplémentaires. Alors, ce n’est plus l’Etat qui garantit via des aides l’indépendance des médias face au marché mais le consommateur-citoyen qui par son abonnement devient le garant du pluralisme.[@jouxPurePlayersMedias2022b] Les modèles économiques alternatifs permettant de sortir du débat la question des actionnaires sont multiples : les fondations (modèle de l'actionnaire-mécène), les sociétés de médias à but non lucratif, ou les coopératives (SCIC) et associations qui permettent une gestion démocratique.[@jouxPurePlayersMedias2022b] Ainsi, Mediapart concilie les deux critiques des médias dominants : la critique anti-hégémonique par son modèle économique et sa production autonome d’informations, et la critique expressiviste en donnant la parole à ses abonnés.[@canuJournalistesLecteurscontributeursMediapart2010]

Aussi, cette nécessité de dépasser la marginalité pour construire un véritable contre-pouvoir médiatique a conduit à un processus de professionnalisation, analysé par Benjamin Ferron et Paola Sedda.[@ferronProfessionnaliserMediasAlternatifs2016]$^,$ [@seddaRessortsDemocratiquesMedias2017] En effet, pour se faire entendre du grand public et ne pas rester un média de niche comme l’ont pu l’être les médias participatifs, la nécessité de se professionnaliser dans un but de légitimation institutionnelle et publique s’est fait sentir. Un exemple est celui de Barricada TV. Ce média, né en Argentine, cherche, contrairement aux médias alternatifs de l’époque, à toucher le grand public et pas seulement les militants. Il fonctionne selon une organisation collective autogérée qui, comme le fera Mediapart, propose un modèle hybride professionnel - amateur en créant des équipes mêlant bénévoles et salariés.[@seddaRessortsDemocratiquesMedias2017] Plus récemment et en France, on observe la création de médias alternatifs adoptant en partie les codes des médias dominants. C’est le cas de *Le Média* qui, tout en adoptant les codes des médias dominants, cherche à les délégitimer.[@tantMEDIAPOPULISTCRITIQUE2021] Cette délégitimation se fait encore aujourd’hui pour les raisons historiques évoquées précédemment. On y retrouve une trop proche proximité et dépendance envers les sources institutionnelles (gouvernement, police), un entre-soi médiatique dans lequel les journalistes des médias dominants sont accusés de former un écosystème clos qui s’auto-alimente en boucle fermée et une structure libérale (appartenance à de riches propriétaires) limitant la liberté éditoriale des journalistes mainstream.[@tantMEDIAPOPULISTCRITIQUE2021] La partialité des médias dominants s’est particulièrement exprimée à travers le traitement médiatique des Gilets Jaunes. Après avoir attiré la curiosité des médias mainstream, un rejet massif en raison de mépris de classe a été opéré par les éditorialistes et politiques ce qui a provoqué un déplacement des pratiques vers les médias alternatifs et les réseaux sociaux.[@tantMEDIAPOPULISTCRITIQUE2021]$^,$ [@granjonGiletsJaunesColeres2021]

Finalement, *Le Média* propose une lecture idéologiquement assumée du champ journalistique dominant. D’abord, comme le démontre Cédric Tant, Le Média construit une dichotomie entre les journalistes mainstream proches des sphères de pouvoir et le peuple, il incarne en cela une approche populiste (opposition peuple et élites dominantes).[@tantMEDIAPOPULISTCRITIQUE2021] Cette critique de la proximité avec le pouvoir est en partie issue de la sociologie actuelle des journalistes mainstream : ils sont sociologiquement proches des classes dirigeantes (CSP+, grandes écoles, etc.)[@neveuSociologieJournalisme], donc sont potentiellement déconnectés du monde réel et vecteurs (peut-être malgré eux) d'une connivence avec le pouvoir.[@tantMEDIAPOPULISTCRITIQUE2021] Ensuite, bien que *Le Média* émette de vives critiques envers le journalisme dominant, il défend tout de même l’idéal journalistique classique. La critique faite par *Le Média* sert à réaffirmer les normes idéales du métier dont les médias alternatifs post-2010 se disent garants : indépendance, liberté d’expression et diversité des points de vue.[@tantMEDIAPOPULISTCRITIQUE2021] Cette critique permet, comme Barricada TV en son temps, de réaffirmer le rôle démocratique des médias qui doivent développer l’esprit critique des citoyens.[@seddaRessortsDemocratiquesMedias2017] L’information doit être un savoir public produite pour le peuple et non pas pour des élites. Cette approche de rupture face aux médias dominants se fait à travers l’utilisation habile des réseaux sociaux numériques et en particulier de YouTube, plateforme devenue un réel espace politique et informationnel que les médias alternatifs comme Le Média cherchent à conquérir.[@douyerePresentationDossierYoutube2019]

### Et constituent un nouvel espace journalistique paradoxal car s’appuyant sur une hétéronomie technique (les plateformes) et journalistique (en cherchant la reconnaissance des médias dominants). {.unnumbered}

Originellement, YouTube n’était qu’une plateforme d’hébergement de vidéos en tous genres qui, rapidement, s’est dédiée au divertissement ou au lifestyle. Cependant, elle est aussi devenue un espace d’expression idéologique et d’engagement politique. Des Youtubeurs politiques, c’est-à-dire des vidéastes citoyens, ont émergé. On y retrouve Usul, Hugo Décrypte ou Bonjour Tristesse qui, à travers la liberté de formats inhérente à YouTube propose un traitement de l’actualité qui se veut différent des journalistes dominants.[@douyerePresentationDossierYoutube2019] Dans cet objectif de faire des médias un vecteur de développement de l’esprit critique des citoyens, on observe sur YouTube le développement de formats longs, sur plan fixe, permettant le déroulé d’interviews de politiques ou d’experts dans lesquelles le fond est prédominant.[@bristielleYouTubeCommeMedia2020] Des thèmes ignorés par les médias dominants comme l’écologie peuvent être imposés, le long format sans contradicteurs permet le développement d’une pensée politique profonde s’appuyant sur une mise en perspective historique et philosophique. YouTube est aussi utilisé pour travailler l’image du politique ou du journaliste car celui devant la caméra sera lié à un sentiment de proximité auprès de l’audience.[@bristielleYouTubeCommeMedia2020]

Aussi, ces Youtubeurs politiques de la première heure s’inscrivent dans une dynamique de la mise en scène de soi militante. Ils ne sont pas que l’incarnation d’un *Nous* collectif mais affirment une singularité individuelle forte, un *Je*, qui pour autant participe à la défense d’une cause commune. La production de soi devient aussi importante que l'objectif politique car l’identification du public au *Je* permet à ce dernier de s’appuyer sur le côté émotionnel des réseaux sociaux pour faire émerger des passions politiques collectives et appuyer un propos qui n’est pas que défendu par des arguments rationnels.[@granjonResistancesLigneMobilisation2017] L’utilisation du pathos sur le YouTube contestataire s’est démocratisé avec le temps. Aujourd’hui on observe une hybridation logos / pathos, une informalisation, par des médias alternatifs tels que *Blast : Le souffle de l’info*, *Le Média* ou Mediapart dont la rhétorique mêle arguments rationnels chiffrés (logos), utilisation massive de données statistiques et commentaires d’universitaires ou experts, ainsi que d’appels émotionnels (pathos) permettant un ancrage dans la réalité des sujets abordés.[@dufourYouTubeContestataire2024] Le traitement médiatique des Gilets Jaunes[@granjonGiletsJaunesColeres2021] ou celui de la réforme des retraites de 2023[@dufourYouTubeContestataire2024] illustrent cela. Ces médias alternatifs ont développé le modèle initié dans les années 2010, obtenant des moyens quasi-professionnels, s’organisant en rédactions collectives bien que les vidéos soient souvent incarnées par des individualités. Il faut aussi noter que le journalisme alternatif et engagé est souvent ancré dans la gauche radicale, alors que le commentaire est plutôt lié à la droite radicale voire souverainiste.[@dufourYouTubeContestataire2024]

Finalement, ces médias alternatifs présents sur le YouTube contestataire constituent un simili-champ journalistique caractérisé par son hétéronomie.[@ferronProfessionnaliserMediasAlternatifs2016] Autrement dit, ce simili-champ est dominé par les règles du champ journalistique dominant. Ses acteurs souhaitent les adopter pour mieux les respecter compte tenu des défaillances considérées comme manifestes du champ journalistique dominant. En se considérant comme un vrai journalisme délaissé par les médias dominants, les acteurs de ces médias gagnent en rétributions symboliques.[@ferronProfessionnaliserMediasAlternatifs2016] Aussi, compte tenu de la structure même de la plateforme YouTube, les médias alternatifs sont caractérisés par une hétéronomie technique. Cela se traduit par l’existence des likes, des commentaires et la volonté de plaire à l’algorithme pour augmenter la diffusion potentielle du contenu. L’action politique et journalistique est formatée par l’outil technique, les internautes militent non seulement pour leurs idées mais aussi avec et contre l’algorithme pour leur donner un maximum de visibilité.[@babeauParticipationPolitiqueCitoyens2014]

\newpage
# Hypothèses et problématisation {.unnumbered}

Ainsi, l’émergence de médias alternatifs numériques tels que Blast ou *Le Média* n’est pas relative qu’à un ajustement technologique mais est issue d’une mutation longue et profonde du champ journalistique. D’abord, la sociologie du journalisme nous permet de comprendre que la crise de confiance envers le champ journalistique dominant est due à sa structure, à son hétéronomie économique (rôle des actionnaires et propriétaires), politique et sociale (les journalistes dominants, sociologiquement déterminés, sont perçus comme des élites déconnectées). Ensuite, les travaux sur le médiactivisme démontrent que la réponse à cette crise se fait d’abord par un expressivisme amateur et participatif. Néanmoins, ce modèle connaît de fortes limites (notamment dans la production autonome d'informations) qui nécessite une professionnalisation des médias alternatifs. Finalement, l’analyse des dispositifs récents met en lumière les paradoxes internes aux médias alternatifs numériques qui cherchent à imiter les codes du journalisme dominant dans une quête de légitimité auprès du grand public tout en les délégitimant et adoptant une informalisation imposée par les plateformes dans une logique de rhétorique militante et de visibilité algorithmique.

Ce paradoxe soulève une énigme sociologique. En diffusant sur Internet, espace souvent décrédibilisé, ces médias souffrent d'un déficit de légitimité institutionnelle face aux médias dominants. Pourtant, la réalité empirique semble contredire cette apparente fragilité. Non seulement ces médias fédèrent des audiences massives, mais ils opèrent une force d'attraction sur le champ professionnel lui-même. Des figures reconnues comme Denis Robert, Salomé Saqué ou Serge Faubert acceptent de quitter le confort matériel et symbolique des rédactions dominantes pour rejoindre ces structures précaires. Aussi, l'hypothèse que nous défendons est que les médias alternatifs (et plus précisément les médias indépendants, numériques et audiovisuels) produisent une rationalité différente pas seulement à cause d'une rhétorique donnée, d'une idéologie ou des agents eux-mêmes. En effet, nous démontrerons dans ce mémoire que c'est le placement structurellement défini des médias alternatifs qui par les conditions de production, les trajectoires professionnelles et le rapport aux sources, génère mécaniquement des logiques discursives différentes. Celles-ci ne sont pas plus émotionnelles ou moins rigoureuses comme l'état de l'art nous laisserait présupposer, mais relève d'une rationalité critique là où les médias dominants produisent une rationalité narrative, rationalités que ce mémoire définira. Notons que nous parlons de rationalité au sens d'opération de mise en ordre du réel.

Alors, nous chercherons donc à répondre à la question suivante : 

> *Comment l’économie des positions dans le champ journalistique impose-t-elle leur mode de rationalité aux médias alternatifs et dominants, à travers une exigence de critique discursive pour les premiers et une fluidité narrative pour les seconds  ?* 

Aussi, notons que dans la suite de ce mémoire, nous emploierons le terme « média alternatifs » pour évoquer les médias indépendants, numériques et audiovisuels. 

# Méthodologie {.unnumbered}


Afin de répondre à notre problématique et compte tenu des contraintes pratiques liés à la production de ce mémoire, nous mènerons notre analyse par l'étude de deux médias alternatifs Blast et *Le média*, et d'un média dominant, France 2. Aussi, nous suivrons une démarche composée à la fois d'une analyse quantitative et qualitative.

## Analyse quantitative {.unnumbered}

Cette analyse quantitative se fera à travers des corpus situés dans le temps (08/02/2026 - 08/04/2026). Pour les médias alternatifs, ce corpus est composé de l'ensemble des transcriptions (générées automatiquement par l'IA de YouTube) des vidéos disponibles sur les chaînes YouTube respectives de chaque média sur la période temporelle précédemment évoquée. Quant au média dominant, le corpus est composé de l'ensemble des Journaux Télévisés de 8h, 13h et 20h de France 2. 

Au delà de ce corpus générique, nous mobiliserons aussi deux sous-corpus. Le premier est lié aux événements survenus début janvier 2026 au Vénézuela (donc un thème d'actualité internationale et externe au corpus générique). Le second est composé des JT et vidéos ayant traité l'affaire Deranque (donc un thème de politique nationale et interne au corpus générique).

Finalement, notons que dans la suite du mémoire, nous mobiliserons régulièrement l'exemple de Mediapart car est souvent mobilisé par les enquêtés. Aussi, il n'est pas un objet en tant que tel de notre corpus mais constitue, plutôt, un cas de référence du modèle économique alternatif.

## Analyse qualitative {.unnumbered}

Afin de compléter cette analyse quantitative qui nous permettra de mieux comprendre comment l’information est traitée par les différents médias, nous appuierons notre analyse sur les agents eux-mêmes. C’est pourquoi, nous mobiliserons quatre entretiens semi-directifs menés auprès de journalistes. La grille utilisée pour mener ces entretiens peut être retrouvée en [Annexe 1](#annexe1) et la table en [Annexe 2](#annexe2) en synthétise le matériau dégagé.  Aussi, il faut noter la diversité de leur profil : un pigiste de Blast, une journaliste web de France 3, une journaliste freelance ayant travaillé pour de nombreux médias dominants et alternatifs, et finalement un data-journaliste du Parisien. Les détails et justifications méthodologiques sur la cohérence des profils étudiés seront donnés par la suite, lors de la mobilisation de chaque entretien. Néanmoins, nous pouvons tout de même évoquer la difficulté d'obtention d'entretiens semi-directifs auprès de journalistes dans le contexte très chargé, pour la profession, des municipales. 

\newpage
# Annonce de plan {.unnumbered}

Pour démontrer notre thèse, nous allons suivre le plan suivant. Dans un premier chapitre, nous montrerons que l’analyse lexicométrique du corpus invalide les prénotions sur l’émotivité des médias alternatifs au profit d’une distinction entre rationalités narrative et critique.

Ensuite, dans un deuxième chapitre, nous démontrerons que la narration et la critique constituent deux fonctions journalistiques opposées qui orientent pré-réflexivement (c'est-à-dire sans que les agents n'objectivent eux-mêmes les règles qu'ils suivent) l'usage des outils rhétoriques dont la légitimité s’adosse à une définition de la neutralité.

Finalement, dans un dernier et troisième chapitre, nous analyserons cette économie des positions dans le champ journalistique qui détermine le mode de pensée et la nature de la production discursive.
